### ISSUE TITLE
Packaged Release

### ISSUE THREAD

**Issue by tjesp** [Odjur/Auc-Stat-BootyBayGazette#1]
Hi, I am using CurseBreaker for addon updates. It support GitHub URLs. 

I get this message when I try to paste this URL:

CB> install https://github.com/Odjur/Auc-Stat-BootyBayGazette

RuntimeError: Failed to parse addon data: https://github.com/Odjur/Auc-Stat-BootyBayGazette
This integration supports only the projects that provide packaged releases.

I am not sure what a packaged release is as I am not using GitHub for any releases, but I wonder if you could support their request?

**Comment by Odjur** [comment]
I just added a release. If it doesn't work let me know, though I don't actively develop this addon anymore so it might take me a bit to respond.
